eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/addPolicy
          filters:
            - AuthenticationFilter
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/deletePolicy/{id}
          filters:
            - AuthenticationFilter
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/findByPolicyF or/{policy_for}
          filters:
            - AuthenticationFilter
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/updatePolicy
          filters:
            - AuthenticationFilter
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/findById/{id}
          filters:
            - AuthenticationFilter
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/getAllPolicyPlans
        - id: announcement-service
          uri: lb://ANNOUNCEMENTSERVICE
          predicates:
            - Path=/announcements/getallannou
        - id: announcement-service
          uri: lb://ANNOUNCEMENTSERVICE
          predicates:
            - Path=/announcements/fetchAnn
        - id: announcement-service
          uri: lb://ANNOUNCEMENTSERVICE
          predicates:
            - Path=/announcements/admin/addAnn
          filters:
            - AuthenticationFilter
        
        
