eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/**
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
          filters:
            - AuthenticationFilter
        - id: wishlist-service
          uri: lb://WISHLIST-SERVICE
          predicates: 
            - Path=/wishlist/**
           
    
