export const REGISTRATION_REQUESTED = "REGISTRATION_REQUESTED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const GET_USER_DATA_REQUESTED = "GET_USER_DATA_REQUESTED";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const GET_POLICIES_REQUESTED = "GET_POLICIES_REQUESTED";
export const GET_POLICIES_SUCCESS = "GET_POLICIES_SUCCESS";
export const GET_POLICIES_FAILED = "GET_POLICIES_FAILED";

export const TEST_REQUESTED = "TEST_REQUESTED";

export const ADD_ANNOUNCEMENT_REQUESTED = "ADD_ANNOUNCEMENT_REQUESTED";
export const ADD_ANNOUNCEMENT_SUCCESS = "ADD_ANNOUNCEMENT_SUCCESS";
export const ADD_ANNOUNCEMENT_FAIL = "ADD_ANNOUNCEMENT_FAIL";

export const GET_ANNOUNCEMENT_REQUESTED = "GET_ANNOUNCEMENT_REQUESTED";
export const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
export const GET_ANNOUNCEMENT_FAIL = "GET_ANNOUNCEMENT_FAIL";

export const GET_USER_POLICIES_REQUESTED = "GET_USER_POLICIES_REQUESTED";
export const GET_USER_POLICIES_SUCCESS = "GET_USER_POLICIES_SUCCESS";
export const GET_USER_POLICIES_FAILED = "GET_USER_POLICIES_FAILED";

export const ADD_USER_POLICIES_REQUESTED = "ADD_USER_POLICIES_REQUESTED";
export const ADD_USER_POLICIES_SUCCESS = "ADD_USER_POLICIES_SUCCESS";
export const ADD_USER_POLICIES_FAILED = "ADD_USER_POLICIES_FAILED";

export const ADD_NEW_POLICY_REQUESTED = "ADD_NEW_POLICY_REQUESTED";
export const ADD_NEW_POLICY_SUCCESS = "ADD_NEW_POLICY_SUCCESS";
export const ADD_NEW_POLICY_FAILED = "ADD_NEW_POLICY_FAILED";

export const GET_POSITION_REQUESTED = "GET_POSITION_REQUESTED";
export const GET_POSITION_SUCCESS = "GET_POSITION_SUCCESS";
export const GET_POSITION_FAILED = "GET_POSITION_FAILED";

export const ADD_POSITION_REQUESTED = "ADD_POSITION_REQUESTED";
export const ADD_POSITION_SUCCESS = "ADD_POSITION_SUCCESS";
export const ADD_POSITION_FAILED = "ADD_POSITION_FAILED";

export const ADD_REVIEW_REQUESTED = "ADD_REVIEW_REQUESTED";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILED = "ADD_REVIEW_FAILED";

export const GET_REVIEW_REQUESTED = "GET_REVIEW_REQUESTED";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAILED = "GET_REVIEW_FAILED";

export const SEND_OTP_REQUESTED = "SEND_OTP_REQUESTED";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";

export const RESET_USER_DATA_MSG = "RESET_USER_DATA_MSG";
export const RESET_OTP_MSG = "RESET_OTP_MSG";
export const RESET_POLICY_MSG = "RESET_POLICY_MSG";
export const RESET_ANN_MSG = "RESET_ANN_MSG";
export const RESET_USER_MSG = "RESET_USER_MSG";
export const RESET_MSG = "RESET_MSG";

export const UPDATE_USER_REQUESTED = "UPDATE_USER_REQUESTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const UPDATE_TESTIMONIAL_REQUESTED = " UPDATE_TESTIMONIAL_REQUESTED";
export const UPDATE_TESTIMONIAL_SUCCESS = " UPDATE_TESTIMONIAL_SUCCESS";
export const UPDATE_TESTIMONIAL_FAILED = " UPDATE_TESTIMONIAL_FAILED";

export const DELETE_TESTIMONIAL_REQUESTED = "DELETE_TESTIMONIAL_REQUESTED";
export const DELETE_TESTIMONIAL_SUCCESS = "DELETE_TESTIMONIAL_SUCCESS";
export const DELETE_TESTIMONIAL_FAILED = "DELETE_TESTIMONIAL_FAILED";

export const GET_ALL_USERS_REQUESTED = "GET_ALL_USERS_REQUESTED";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";

export const POST_QUERY_REQUESTED = "POST_QUERY_REQUESTED";
export const POST_QUERY_SUCCESS = "POST_QUERY_SUCCESS";
export const POST_QUERY_FAILED = "POST_QUERY_FAILED";

export const RESET_QUERY_MSG = "RESET_QUERY_MSG";

export const ADMIN_LOGIN_REQUESTED = "ADMIN_LOGIN_REQUESTED";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED";

export const RESET_ADMIN_MSG = "RESET_ADMIN_MSG";
export const RESET_USERDATA_MSG = "RESET_USERDATA_MSG";